"""Excel export mirroring the Azure Pricing Calculator Export template.

Two sheets:

1. **Estimate** — Microsoft's Azure Pricing Calculator column schema
   (Service category / Service name / Type / Custom name / Region /
   Description / Estimated upfront cost / Estimated monthly cost).

2. **Cost Assumptions** — audit trail for every row: rate × quantity +
   any discount / licensing / tiering tags that produced the monthly
   cost. Builders with rich context populate `BomLine.assumption`
   directly; the rest are synthesized by `derive_assumption()`.

Plus a compact header at the top of each sheet with currency, total,
and generation date.
"""
from __future__ import annotations

import datetime as _dt
import io
from typing import List

import pandas as pd

from ..models import BomLine
from .assumptions import assumption_row
from .naming import derive_custom_name, derive_service_name


ESTIMATE_COLUMNS = [
    "Service category",
    "Service name",
    "Type",
    "Custom name",
    "Region",
    "Description",
    "Estimated upfront cost",
    "Estimated monthly cost",
]

ASSUMPTION_COLUMNS = [
    "Service category",
    "Service name",
    "Type",
    "Custom name",
    "Resource",
    "Assumption",
    "Unit price",
    "Quantity",
    "Unit",
    "Monthly cost",
]


def _row_for(line: BomLine, app_name: str = "") -> dict:
    service_name = line.service_name or derive_service_name(line.category, line.resource)
    custom_name = line.custom_name or derive_custom_name(line.category, line.resource, app_name=app_name)
    type_text = line.sku or line.meter or ""
    return {
        "Service category": line.category,
        "Service name": service_name,
        "Type": type_text,
        "Custom name": custom_name,
        "Region": line.region,
        "Description": line.resource,
        "Estimated upfront cost": 0.0,
        "Estimated monthly cost": round(float(line.monthly_cost), 2),
    }


def build_excel_bom(
    lines: List[BomLine],
    mapping_rows: List[dict],  # retained for API compat; not written to Excel
    region: str,
    currency: str,
    app_name: str = "",
    global_assumptions: List[str] = None,
) -> bytes:
    """Build the Excel workbook with Estimate + Cost Assumptions sheets.

    `global_assumptions` is an optional list of cross-cutting assumption
    strings (missing-key-info defaults, Power BI user → Fabric SKU
    recommendation, etc.) that apply to the overall assessment and don't
    belong to a single line item. They're rendered as an "Assessment-wide
    assumptions" block at the top of the Cost Assumptions sheet.
    """
    global_assumptions = global_assumptions or []
    rows = [_row_for(l, app_name=app_name) for l in lines]
    df = pd.DataFrame(rows, columns=ESTIMATE_COLUMNS)
    total = round(df["Estimated monthly cost"].sum(), 2) if not df.empty else 0.0

    assumption_rows = [assumption_row(l, app_name=app_name) for l in lines]
    df_assump = pd.DataFrame(assumption_rows, columns=ASSUMPTION_COLUMNS)

    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="xlsxwriter") as xw:
        # ---------- Sheet 1: Estimate ----------
        header = pd.DataFrame(
            [
                ["Estimate generated by", "azure-bom-generator"],
                ["Generated at", _dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
                ["Application / workload", app_name or "(not set)"],
                ["Billing region", region],
                ["Currency", currency],
                ["Billing frequency", "Monthly"],
                ["Total estimated monthly cost", total],
            ],
            columns=["Field", "Value"],
        )
        header.to_excel(xw, sheet_name="Estimate", index=False, startrow=0)
        start_row = len(header) + 3
        df.to_excel(xw, sheet_name="Estimate", index=False, startrow=start_row)

        ws = xw.sheets["Estimate"]
        ws.set_column(0, 0, 22)  # Service category
        ws.set_column(1, 1, 28)  # Service name
        ws.set_column(2, 2, 26)  # Type
        ws.set_column(3, 3, 28)  # Custom name
        ws.set_column(4, 4, 16)  # Region
        ws.set_column(5, 5, 48)  # Description
        ws.set_column(6, 6, 20)  # Upfront
        ws.set_column(7, 7, 22)  # Monthly

        # ---------- Sheet 2: Cost Assumptions ----------
        #
        # Structure:
        #   Rows  0 ..        : Assessment-wide assumptions (global list)
        #   Rows N+3 ..       : Per-line assumption table
        #
        # Every line item gets a row so a reviewer can audit rate × qty +
        # any discount / licensing / tiering tags that produced the cost.
        wa_rows = [{"#": i + 1, "Assumption": a} for i, a in enumerate(global_assumptions)]
        if not wa_rows:
            wa_rows = [{"#": 1, "Assumption": "(none)"}]
        df_global = pd.DataFrame(wa_rows, columns=["#", "Assumption"])

        section_header = pd.DataFrame(
            [["Assessment-wide assumptions"]], columns=["Section"],
        )
        section_header.to_excel(xw, sheet_name="Cost Assumptions", index=False, startrow=0)
        df_global.to_excel(xw, sheet_name="Cost Assumptions", index=False, startrow=2)

        per_line_start = 2 + len(df_global) + 3
        pd.DataFrame(
            [["Per-line assumptions"]], columns=["Section"],
        ).to_excel(xw, sheet_name="Cost Assumptions", index=False, startrow=per_line_start)
        df_assump.to_excel(
            xw, sheet_name="Cost Assumptions", index=False, startrow=per_line_start + 2,
        )

        ws2 = xw.sheets["Cost Assumptions"]
        ws2.set_column(0, 0, 22)   # Service category / index
        ws2.set_column(1, 1, 28)   # Service name
        ws2.set_column(2, 2, 22)   # Type
        ws2.set_column(3, 3, 28)   # Custom name
        ws2.set_column(4, 4, 44)   # Resource
        ws2.set_column(5, 5, 90)   # Assumption (widest — the point of the sheet)
        ws2.set_column(6, 6, 14)   # Unit price
        ws2.set_column(7, 7, 14)   # Quantity
        ws2.set_column(8, 8, 16)   # Unit
        ws2.set_column(9, 9, 18)   # Monthly cost

    return buf.getvalue()
