"""Excel export mirroring the Azure Pricing Calculator Export template.

One sheet — "Estimate" — with the columns Microsoft's calculator exports:

    Service category | Service name | Type | Custom name | Region |
    Description | Estimated upfront cost | Estimated monthly cost

Plus a compact header at the top with currency, total, and generation date.
"""
from __future__ import annotations

import datetime as _dt
import io
from typing import List

import pandas as pd

from ..models import BomLine
from .naming import derive_custom_name, derive_service_name


ESTIMATE_COLUMNS = [
    "Service category",
    "Service name",
    "Type",
    "Custom name",
    "Region",
    "Description",
    "Estimated upfront cost",
    "Estimated monthly cost",
]


def _row_for(line: BomLine, app_name: str = "") -> dict:
    service_name = line.service_name or derive_service_name(line.category, line.resource)
    custom_name = line.custom_name or derive_custom_name(line.category, line.resource, app_name=app_name)
    type_text = line.sku or line.meter or ""
    return {
        "Service category": line.category,
        "Service name": service_name,
        "Type": type_text,
        "Custom name": custom_name,
        "Region": line.region,
        "Description": line.resource,
        "Estimated upfront cost": 0.0,
        "Estimated monthly cost": round(float(line.monthly_cost), 2),
    }


def build_excel_bom(
    lines: List[BomLine],
    mapping_rows: List[dict],  # retained for API compat; not written to Excel
    region: str,
    currency: str,
    app_name: str = "",
) -> bytes:
    rows = [_row_for(l, app_name=app_name) for l in lines]
    df = pd.DataFrame(rows, columns=ESTIMATE_COLUMNS)
    total = round(df["Estimated monthly cost"].sum(), 2) if not df.empty else 0.0

    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="xlsxwriter") as xw:
        # Write the estimate with a small header block, mirroring MS export shape
        header = pd.DataFrame(
            [
                ["Estimate generated by", "azure-bom-generator"],
                ["Generated at", _dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
                ["Application / workload", app_name or "(not set)"],
                ["Billing region", region],
                ["Currency", currency],
                ["Billing frequency", "Monthly"],
                ["Total estimated monthly cost", total],
            ],
            columns=["Field", "Value"],
        )
        header.to_excel(xw, sheet_name="Estimate", index=False, startrow=0)

        # Main line-item table starts a few rows below the header
        start_row = len(header) + 3
        df.to_excel(xw, sheet_name="Estimate", index=False, startrow=start_row)

        ws = xw.sheets["Estimate"]
        ws.set_column(0, 0, 22)  # Service category
        ws.set_column(1, 1, 28)  # Service name
        ws.set_column(2, 2, 26)  # Type
        ws.set_column(3, 3, 28)  # Custom name
        ws.set_column(4, 4, 16)  # Region
        ws.set_column(5, 5, 48)  # Description
        ws.set_column(6, 6, 20)  # Upfront
        ws.set_column(7, 7, 22)  # Monthly

    return buf.getvalue()
